[tool.poetry]
name = "c-base-org-lektor"
version = "0.1.0"
description = "A c-base.org based in the lektor static site generator."
authors = ["Uwe Kamper <me@uwekamper.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
lektor = "^3.2.0"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
